"""Initial schema

Revision ID: 0e288514752e
Revises: 
Create Date: 2026-08-19 14:18:46.191090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.models


# revision identifiers, used by Alembic.
revision: str = '0e288514752e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memory_key', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memory_id'), 'agent_memory', ['id'], unique=False)
    op.create_index(op.f('ix_agent_memory_memory_key'), 'agent_memory', ['memory_key'], unique=False)
    op.create_table('content_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('cta', sa.String(length=500), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('content_angle', sa.String(length=100), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('video_prompt', sa.Text(), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('target_platform', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('published_time', sa.DateTime(), nullable=True),
    sa.Column('meta_facebook_post_id', sa.String(length=255), nullable=True),
    sa.Column('meta_instagram_post_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_posts_id'), 'content_posts', ['id'], unique=False)
    op.create_index(op.f('ix_content_posts_scheduled_time'), 'content_posts', ['scheduled_time'], unique=False)
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.String(length=20), nullable=True),
    sa.Column('target_posts_count', sa.Integer(), nullable=True),
    sa.Column('image_ratio', sa.Float(), nullable=True),
    sa.Column('reel_ratio', sa.Float(), nullable=True),
    sa.Column('carousel_ratio', sa.Float(), nullable=True),
    sa.Column('educational_pct', sa.Integer(), nullable=True),
    sa.Column('entertainment_pct', sa.Integer(), nullable=True),
    sa.Column('promotional_pct', sa.Integer(), nullable=True),
    sa.Column('focus_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_id'), 'strategy', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_target_date'), 'strategy', ['target_date'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_agent_name'), 'system_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facebook_page_id', sa.String(length=255), nullable=True),
    sa.Column('facebook_access_token', backend.models.EncryptedText(), nullable=True),
    sa.Column('instagram_account_id', sa.String(length=255), nullable=True),
    sa.Column('instagram_access_token', backend.models.EncryptedText(), nullable=True),
    sa.Column('page_category', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('page_about', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('growth_goal', sa.Text(), nullable=True),
    sa.Column('tone_of_voice', sa.String(length=255), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('gemini_api_key', sa.String(length=255), nullable=True),
    sa.Column('virtux_api_key', sa.String(length=255), nullable=True),
    sa.Column('auto_mode_enabled', sa.Boolean(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('trend_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('format_type', sa.String(length=100), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_memory_id'), 'trend_memory', ['id'], unique=False)
    op.create_index(op.f('ix_trend_memory_topic'), 'trend_memory', ['topic'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('analytics_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('watch_time_seconds', sa.Integer(), nullable=True),
    sa.Column('follower_growth', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['content_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_data_id'), 'analytics_data', ['id'], unique=False)
    op.create_table('connected_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('facebook_page_id', sa.String(length=255), nullable=True),
    sa.Column('facebook_page_name', sa.String(length=255), nullable=True),
    sa.Column('facebook_access_token', backend.models.EncryptedText(), nullable=True),
    sa.Column('instagram_account_id', sa.String(length=255), nullable=True),
    sa.Column('instagram_account_name', sa.String(length=255), nullable=True),
    sa.Column('page_category', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('page_about', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('growth_goal', sa.Text(), nullable=True),
    sa.Column('tone_of_voice', sa.String(length=255), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('is_active_growth', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connected_pages_facebook_page_id'), 'connected_pages', ['facebook_page_id'], unique=False)
    op.create_index(op.f('ix_connected_pages_id'), 'connected_pages', ['id'], unique=False)
    op.create_table('publishing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['content_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_logs_id'), 'publishing_logs', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_publishing_logs_id'), table_name='publishing_logs')
    op.drop_table('publishing_logs')
    op.drop_index(op.f('ix_connected_pages_id'), table_name='connected_pages')
    op.drop_index(op.f('ix_connected_pages_facebook_page_id'), table_name='connected_pages')
    op.drop_table('connected_pages')
    op.drop_index(op.f('ix_analytics_data_id'), table_name='analytics_data')
    op.drop_table('analytics_data')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trend_memory_topic'), table_name='trend_memory')
    op.drop_index(op.f('ix_trend_memory_id'), table_name='trend_memory')
    op.drop_table('trend_memory')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_agent_name'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_strategy_target_date'), table_name='strategy')
    op.drop_index(op.f('ix_strategy_id'), table_name='strategy')
    op.drop_table('strategy')
    op.drop_index(op.f('ix_content_posts_scheduled_time'), table_name='content_posts')
    op.drop_index(op.f('ix_content_posts_id'), table_name='content_posts')
    op.drop_table('content_posts')
    op.drop_index(op.f('ix_agent_memory_memory_key'), table_name='agent_memory')
    op.drop_index(op.f('ix_agent_memory_id'), table_name='agent_memory')
    op.drop_table('agent_memory')
    # ### end Alembic commands ###
